module.exports = {
	"PORT": 3003,
	"host":"http://localhost:3003",
	"j_username":'sushant@anscommerce.com',
	"j_password":'daksh@puri26',
	"url":'https://auth.unicommerce.com/login',
	"projects":{'9':'secretwish'},
	"maven_url": "https://anssecretwish.gscmaven.com",
	"maven_auth_email": "apiintegration@anssecretwish.com",
	"maven_auth_password": "abcd@1234",
    "project_name":"express-mvc-generator",
	"adminname": "Sumit",
	"adminmail": "sumit.shairya@gmail.com",
	'email_smtp_host':'Your Email SMTP',
	'email_smtp_port':'YOUR SMTP PORT',
	"smtp_from_eamil":"from@email.com",
	"smtp_from_name":"express-mvc-generator",
	"alert_email":"sumit.shairya@email.com",
	"alert_email_name":"MyApp"
};